BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE,
  password text NOT NULL,
  is_admin boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS needs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL,
  category text NOT NULL,
  needed_by date,
  event_date date,
  event_time text,
  event_location text,
  status text NOT NULL DEFAULT 'FLOATING',
  estimated_cost integer,
  need_type text NOT NULL DEFAULT 'ONETIME',
  start_date date,
  end_date date,
  image_url text,
  redirect_url text,
  volunteers_needed integer,
  volunteers_count integer DEFAULT 0,
  is_highlighted boolean DEFAULT false,
  recipient_name text,
  recipient_phone text,
  recipient_email text,
  recipient_address text,
  recipient_notes text,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now(),
  CONSTRAINT needs_status_check CHECK (status IN ('DRAFT', 'FLOATING', 'PLEDGED', 'FULFILLED', 'RECURRING')),
  CONSTRAINT needs_category_check CHECK (category IN ('FOOD', 'CLOTHING', 'SERVICE', 'EDUCATION', 'HOUSING', 'EVENT', 'OTHER')),
  CONSTRAINT needs_type_check CHECK (need_type IN ('ONETIME', 'ONGOING', 'GROUP'))
);

CREATE TABLE IF NOT EXISTS pledges (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  need_id integer NOT NULL REFERENCES needs (id) ON DELETE CASCADE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text NOT NULL,
  phone text,
  organization text,
  notes text,
  donation_type text NOT NULL,
  is_ongoing_commitment boolean,
  subscribe_to_emails boolean DEFAULT true,
  payment_completed boolean DEFAULT false,
  created_at timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS admin_notification_preferences (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
  receive_all_notifications boolean NOT NULL DEFAULT true,
  enabled_categories text NOT NULL DEFAULT '[]',
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);

-- Calendar domain tables (migrated from standalone clh-calendar app)
CREATE TABLE IF NOT EXISTS calendar_event_series (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id text NOT NULL DEFAULT 'clh',
  title text NOT NULL,
  group_name text,
  location text,
  description_html text NOT NULL DEFAULT '',
  event_color text NOT NULL DEFAULT '#2563eb',
  text_color text NOT NULL DEFAULT '#ffffff',
  all_day boolean NOT NULL DEFAULT false,
  starts_at timestamptz NOT NULL,
  ends_at timestamptz NOT NULL,
  timezone text NOT NULL DEFAULT 'America/New_York',
  recurrence_rule text,
  recurrence_until timestamptz,
  integration_source text,
  integration_key text,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT calendar_event_series_time_check CHECK (ends_at > starts_at)
);

CREATE TABLE IF NOT EXISTS calendar_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id text NOT NULL DEFAULT 'clh',
  series_id uuid REFERENCES calendar_event_series (id) ON DELETE CASCADE,
  occurrence_start timestamptz NOT NULL,
  occurrence_end timestamptz NOT NULL,
  title_override text,
  location_override text,
  description_html_override text,
  all_day_override boolean,
  status text NOT NULL DEFAULT 'ACTIVE',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT calendar_events_time_check CHECK (occurrence_end > occurrence_start)
);

CREATE TABLE IF NOT EXISTS calendar_audit_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id text NOT NULL DEFAULT 'clh',
  event_type text NOT NULL,
  entity_type text,
  entity_id uuid,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  idempotency_key text,
  request_path text,
  http_method text,
  response_status integer,
  response_payload jsonb,
  webhook_status text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Required by connect-pg-simple (express-session store)
CREATE TABLE IF NOT EXISTS "session" (
  sid varchar PRIMARY KEY,
  sess json NOT NULL,
  expire timestamp(6) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_needs_status ON needs (status);
CREATE INDEX IF NOT EXISTS idx_needs_created_at ON needs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pledges_need_id ON pledges (need_id);
CREATE INDEX IF NOT EXISTS idx_admin_notification_preferences_user_id ON admin_notification_preferences (user_id);
CREATE INDEX IF NOT EXISTS idx_session_expire ON "session" (expire);
CREATE INDEX IF NOT EXISTS idx_calendar_event_series_org_starts ON calendar_event_series (org_id, starts_at);
CREATE INDEX IF NOT EXISTS idx_calendar_event_series_recurrence ON calendar_event_series (org_id, recurrence_rule) WHERE recurrence_rule IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_calendar_event_series_org_group_name ON calendar_event_series (org_id, group_name) WHERE group_name IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_calendar_event_series_integration_unique ON calendar_event_series (org_id, integration_source, integration_key) WHERE integration_source IS NOT NULL AND integration_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_calendar_events_org_occurrence ON calendar_events (org_id, occurrence_start);
CREATE INDEX IF NOT EXISTS idx_calendar_audit_org_created ON calendar_audit_log (org_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_calendar_audit_idempotency ON calendar_audit_log (org_id, idempotency_key, http_method, request_path) WHERE idempotency_key IS NOT NULL;

-- Security: public schema is exposed through PostgREST in Supabase.
-- Enable RLS so tables are not externally accessible without explicit policies.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE needs ENABLE ROW LEVEL SECURITY;
ALTER TABLE pledges ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_notification_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE "session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS admin_magic_login_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS auth_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS calendar_sync_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS calendar_event_series ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS calendar_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS calendar_audit_log ENABLE ROW LEVEL SECURITY;

COMMIT;
